### ISSUE TITLE
Rename?

### ISSUE THREAD

**Issue by srid** [shivaraj-bh/ollama-flake#2]
I've never seen the `nixify` prefix used to describe Nix packaging repo names.

Maybe `ollama-nix`

If this project ends up doing more than packaging ollama, we might even give it an unique name, like https://github.com/tweag/jupyenv

**Comment by shivaraj-bh** [comment]
I am okay with `ollama-nix` for now

**Comment by shivaraj-bh** [comment]
perhaps even `ollama-flake`
