### ISSUE TITLE
Dependency on `qtbase` ?

### ISSUE THREAD

**Issue by drupol** [shivaraj-bh/ollama-flake#6]
Hello,

I tested this flake and I noticed that it took a while to compile `qtbase`. Therefore, I'm wondering why `qtbase` is required. Can you help?

**Comment by shivaraj-bh** [comment]
This is the relation:

```sh
> nix why-depends /nix/store/gax8zszav98v5knqm41c3aid3lw8iy8l-default.drv /nix/store/0fhwyx0y71sj5fb46lciam253vcxz92f-qtbase-6.7.1.drv
/nix/store/gax8zszav98v5knqm41c3aid3lw8iy8l-default.drv
└───/nix/store/q0fwsmzzg94b3g64b4675nv226sfjhff-process-compose-default.json.drv
    └───/nix/store/54mpr9bj24y830fggb91qid6jcx8cdwb-open-webui-wrapper.drv
        └───/nix/store/fvvzrwc41smgs03pkmhrgkydawz881rz-open-webui.drv
            └───/nix/store/p2miki7z4ps9lkjycqjlvbb6dqqa4qym-python3-3.10.14-env.drv
                └───/nix/store/f2hk9j6fd1iak660k941hrwj28rli644-python3.10-opencv-python-4.9.0.80.drv
                    └───/nix/store/0fhwyx0y71sj5fb46lciam253vcxz92f-qtbase-6.7.1.drv
```

I observed the rebuild while updating the `nixpkgs` of `example/cpu` yesterday. Then I checked if hydra-check fails for qtbase:
```sh
nix run github:nix-community/hydra-check -- qt6.qtbase --arch aarch64-darwin
Build Status for qt6.qtbase.aarch64-darwin on jobset nixpkgs/trunk
✔ qtbase-6.7.1 from 2024-05-22 - https://hydra.nixos.org/build/260396540
```

But it doesn’t .

I think there is no cache for the qtbase in `nixpkgs-unstable`and the hydra-check could be for `master`?

**Comment by drupol** [comment]
Perhaps it would be better to rely on `nixos-unstable`?

**Comment by shivaraj-bh** [comment]
Will it be any different? I thought [both of them follow master and lag behind a couple of days](https://github.com/NixOS/nixpkgs/blob/2f0bb201ce79ca11eeaa929b0b3161d6f9b7807e/doc/preface.chapter.md?plain=1#L36-L41)? Is there anything more that I might be missing? Also since I am aiming to support both `Linux` and `macOS`, I thought I should go with `nixpkgs-unstable`.

**Comment by shivaraj-bh** [comment]
Its not rebuilding qtbase anymore, I updated to the latest `nixpkgs-unstable`: https://github.com/shivaraj-bh/ollama-flake/commit/483f6f0c1104deff36c25acc940c906607dd705b

**Comment by drupol** [comment]
Cool let me try.

**Comment by drupol** [comment]
Looks like it's fixed. Thanks!
